import { ObjObjMap } from '@Types';

export const i18n: ObjObjMap = {
    en: {
        Likes: 'Likes',
        Going: 'Going',
        Past: 'Past',
        Details: 'Details',
        Participants: 'Participants',
        Commens: 'Commens',
        'invalid token': 'Invalid token, login again',
        slogan: 'FIND THE MOST LOVED ACTIVITIES',
        appName: 'BLACK CAT',
        passwordPlaceholder: 'Password',
        usernamePlaceholder: 'Username',
        login: 'SIGN IN',
        'Channel All activities anytime': 'Channel All activities anytime',
        anytime: 'ANYTIME',
        today: 'TODAY',
        tomorrow: 'TOMORROW',
        yestoday: 'Yestoday',
        '{0} days ago': '{0} days ago',
        '{0} hours ago': '{0} hours ago',
        '{0} minutes ago': '{0} minutes ago',
        justnow: 'just now',
        all: 'All',
        'next 7 days': 'NEXT 7 DAYS',
        'next 30 days': 'NEXT 30 DAYS',
        later: 'LATER',
        'Channel {0} activities anytime': 'Channel {0} activities anytime',
        'Channel {0} activities form {1} to {2}':
            'Channel {0} activities form {1} to {2}',
        date: 'DATE',
        channel: 'CHANNEL',
        search: 'SEARCH',
        '{0}publishe': 'Published {0}',
        when: 'When',
        where: 'Where',
        joined: 'I am going',
        join: 'JOIN',
        'I am going!': 'I am going!',
        'I like it': 'I like it',
        'Leave your comment here': 'Leave your comment here',
        'Search Results': 'Search Results',
        'CLEAR SEARCH': 'CLEAR SEARCH',
        'Search for {0}': 'Search for {0}',
        'No activity found': 'No activity found',
        'Loading...': 'Loading...',
    },
    zh: {
        Likes: '喜欢',
        Going: '参与',
        Past: '历史',
        Details: '详情',
        Participants: '参与',
        Commens: '评论',
        'invalid token': 'Token已失效，请重新登陆',
        slogan: '发现你喜欢的活动',
        appName: '黑猫',
        passwordPlaceholder: '密码',
        usernamePlaceholder: '用户名',
        login: '登陆',
        'Channel All activities anytime': '任意时间所有频道的活动',
        anytime: '任意时间',
        today: '今天',
        tomorrow: '明天',
        yestoday: '昨天',
        '{0} days ago': '{0}天前',
        '{0} hours ago': '{0}小时前',
        '{0} minutes ago': '{0}分钟前',
        justnow: '刚刚',
        all: '所有频道',
        'next 7 days': '后续7天',
        'next 30 days': '后续30天',
        later: '之后',
        'Channel {0} activities anytime': '任意时间{0}频道的活动',
        'Channel {0} activities form {1} to {2}': '{1}至{2} {0}频道的活动',
        date: '日期',
        channel: '频道',
        search: '搜索',
        '{0}publishe': '{0}发布',
        when: '时间',
        where: '地点',
        joined: '我已参与',
        'I am going!': '我已参与',
        'I like it': '我喜欢',
        join: '参与',
        'Leave your comment here': '输入你的评论',
        'Search Results': '搜索结果',
        'CLEAR SEARCH': '重置搜索',
        'Search for {0}': '{0} 的搜索结果',
        'No activity found': '未发现活动结果',
        'Loading...': '加载中...',
    },
};
